sudo: required
services:
  - docker

before_install:
  - docker build -t dmsanthosh/docker-react -f Dockerfile.test .

script:
  - docker run -e CI=true dmsanthosh/docker-react npm run test -- --coverage