version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app
#  tests:
#    tty: true
#    stdin_open: true
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#    volumes:
#    - /app/node_modules
#    - .:/app
#    command: ["npm", "run", "test"]